### PR TITLE
Feature1

### PR DESCRIPTION
**Pull request by Brenda309**
On this Project:
 1. I created a new repository.
 2. I created a new branch
 3. I added a gitignore file
 4. Set-up a linters for html&CSS
 5. added Html. index file
 6. add style.css file.
 7. created test.md and I untracked it.

### CODE REVIEW

**Review by mateo951 — CHANGES_REQUESTED** [review]
### Hi @Brenda309, 

📝👌 **Your project highlights** 🔥😎 
- Nice README file 🚀
- Use of GitHub Flow ✔

Welcome to Microverse and congrats on making your first project 💪😎

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)_

**Comment by mateo951** [comment]
There are some issues with the setup of your linters that are resulting in not being triggered by Github actions 😥

Example of linters being triggered 🧐
Captura2
 
Hint 😉 Check out that the directory structure is properly setup 
**Correct structure** `.github/workflows/linters.yml`
#### As the instruction asks: 
_...create a .github/workflows folder and add a copy of [.github/workflows/linters.yml](https://github.com/microverseinc/linters-config/blob/master/html-css/.github/workflows/linters.yml) to that folder._

You are missing one file in the directory structure of the linters 👀 Also, kindly double-check that there are no typos once you copy the content of that file into yours 🤓

**Comment by mateo951** [comment]
Kindly make sure that you ignore test.md and node_modules directory so we practice for the near future when we work with dependencies and to meet with the project requirements🧐

image

**Comment by mateo951** [comment]
### OPTIONAL - All of the suggestions inside this comment are optional 👀

You did pretty well writing your summary on your PR's description so this is just an optional/suggestion for your future PRs to improve the structure and flow of it 🙌 

For example, you could go with something like this 🤓
  - Added setup for linters
  - Added gitignore file with ignored files/directories 
  - Added main structure (index.html / style.css)
  - Modified hypothetical.file 😉

Also, you could simplify your title to make your PR clearer such as
**Leaderboard: Setup**  _(Name of Project: Feature introduced in branch)_

Another suggestion to improve your near future PRs 💪🤓
Try making the name of your feature branch a little bit more descriptive. So in this instance, instead of feature1, that for an external user doesn't give them much info of the branch, you could go with something like feature-setup 🧐

**Comment by Brenda309** [comment]
Hello Mateo, Thank you so much for the feedback, I really appreciate it. Unfortunately, I made some improvements but I am not able to submit it again because the status is still at review pending. Is there a missing step on your side, or it's on my side, or it's system behavior?

**Pull request closed without merging**
